title: An Introduction to Solving Biological Problems with Python
description: based on the University of Cambridge Python Course
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
